apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-quizmaster-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-quizmaster
  template:
    metadata:
      labels:
        app: devops-quizmaster
    spec:
      containers:
      - name: app
        image: __IMAGE_PLACEHOLDER__
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-quizmaster-svc
spec:
  type: LoadBalancer
  selector:
    app: devops-quizmaster
  ports:
  - port: 80
    targetPort: 80
