apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-quizmaster-deployment
  labels:
    app: devops-quizmaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-quizmaster
  template:
    metadata:
      labels:
        app: devops-quizmaster
    spec:
      containers:
      - name: app
        image: __IMAGE_PLACEHOLDER__    # Jenkins will replace this
        imagePullPolicy: Always
        ports:
        - containerPort: 80
