apiVersion: v1
kind: Service
metadata:
  name: devops-quizmaster-svc
spec:
  type: NodePort
  selector:
    app: devops-quizmaster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
